Do not generate every token in the specified time-window
hectorm/otpauth pull request #488
Opened 2024-04-17 08:32 UTC by air2

This will immidiatly return when a correct token is found. It will also start with comparing the token against the one for the current time, then 1 token before the current time, 1 after, 2 before the current time etc.. until the complete window is compared or  a valid  token is found. 

This should improve performance, because most of the time the current token or the previous token is submitted.

This should fix #487

2024-04-17 19:34 UTC, hectorm requested changes

2024-04-17 20:38 UTC, air2 commented on src/hotp.js
> +    for (let i = 0; i <= window && delta === null; ++i) {
You are totally right, I will fix and test this tomorrow

2024-04-19 14:09 UTC, hectorm approved these changes

2024-04-19 14:11 UTC, merged

2024-04-19 17:12 UTC, air2 commented
Thank you for the fast response and the work on this package!